### ISSUE TITLE
What means </s>?

### ISSUE THREAD

**Issue by bledson** [nathanshartmann/portuguese_word_embeddings#4]
By any chance this has a special meaning like 'unk' for rare/unknown words?

**Comment by nathanshartmann** [comment]
This token probably came from a UGC corpus like subtitles. Unfortunately, because our corpus is too huge, there are wrong tokens that were not removed in preprocessing step. The same happens in embedding models for English.

Hope I have answered your question.

Nathan Siegle Hartmann

Em 16 de mai de 2018, à(s) 22:57, Bledson Kivy <notifications@github.com> escreveu:

**Comment by bledson** [comment]
Thanks! It was exactly that.
